services:
  pipelinerunner:
    image: pipelinerunner
    container_name: pipelinerunner
    build: 
      context: ./
      dockerfile: ./containers/pipelinerunner/Dockerfile
    volumes:
      - ./:/code
    environment:
      DATABASE_NAME: ${DATABASE_NAME}
      MOTHERDUCK_TOKEN: ${MOTHERDUCK_TOKEN}

 